//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sample.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NVOrderRows
    {
        public int OrderID { get; set; }
        public System.DateTime OrderDate { get; set; }
        public string CompanyID { get; set; }
        public long ISBN { get; set; }
        public string BookName { get; set; }
        public decimal Price { get; set; }
        public string Season { get; set; }
        public string CustReference { get; set; }
    
        public virtual Selection Selection { get; set; }
        public virtual Users Users { get; set; }
    }
}
