//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SampleSelection.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cart
    {
        public int OrderID { get; set; }
        public System.DateTime OrderDate { get; set; }
        public int CompanyID { get; set; }
        public long ISBN { get; set; }
        public string BookName { get; set; }
        public decimal Price { get; set; }
        public string CustRef { get; set; }
        public bool IsInCart { get; set; }
    }
}
